.pragma library

var data = {
    "defaultModel": "",
    "customEndpoint": "",
    "customCurlTemplate": "",
    "customName": "",
    "customModels": [],
    "customModelsJson": "[]",
    "manualModelsJson": "{}",
    "extraModels": [],
    "defaultModels": {
        "openai": "",
        "anthropic": "",
        "gemini": "",
        "openrouter": "",
        "ollama": "",
        "custom": ""
    },
    "ignoreModelCatalog": {
        "openai": false,
        "anthropic": false,
        "gemini": false,
        "openrouter": false,
        "ollama": false,
        "custom": false
    },
    "workspace": "",
    "overlayWidth": 640,
    "overlayAnchor": "top",
    "overlayOffsetX": 0,
    "overlayOffsetY": 0,
    "showScrim": true,
    "enabledTools": [
        "read_files",
        "grep",
        "file_glob",
        "apply_file_diffs",
        "run_shell_command",
        "ask_user_question",
        "read_skill",
        "exa_search",
        "exa_contents",
        "native"
    ],
    "commands": [],
    "contextProviders": {
        "focusedWindow": true,
        "clipboard": false,
        "notifications": false,
        "weather": false,
        "resources": false
    },
    "executionProfile": {
        "readFiles": "AgentDecides",
        "applyCodeDiffs": "AlwaysAsk",
        "executeCommands": "AgentDecides",
        "askUserQuestion": "AlwaysAsk",
        "computerUse": "Never",
        "commandAllowlist": [
            "cat(\\s.*)?",
            "echo(\\s.*)?",
            "find .*",
            "grep(\\s.*)?",
            "ls(\\s.*)?",
            "which .*",
            "uname(\\s.*)?",
            "hostname(\\s.*)?",
            "whoami(\\s.*)?",
            "pwd(\\s.*)?",
            "date(\\s.*)?",
            "id(\\s.*)?",
            "df(\\s.*)?",
            "free(\\s.*)?",
            "uptime(\\s.*)?",
            "arch(\\s.*)?",
            "nproc(\\s.*)?",
            "true(\\s.*)?",
            "false(\\s.*)?"
        ],
        "commandDenylist": [
            "bash(\\s.*)?",
            "fish(\\s.*)?",
            "pwsh(\\s.*)?",
            "sh(\\s.*)?",
            "zsh(\\s.*)?",
            "curl(\\s.*)?",
            "eval(\\s.*)?",
            "exec(\\s.*)?",
            "source(\\s.*)?",
            "wget(\\s.*)?",
            "dig(\\s.*)?",
            "nslookup(\\s.*)?",
            "host(\\s.*)?",
            "ssh(\\s.*)?",
            "scp(\\s.*)?",
            "rsync(\\s.*)?",
            "telnet(\\s.*)?",
            "rm(\\s.*)?"
        ],
        "directoryAllowlist": [],
        "webSearchEnabled": true
    },
    "jev": {
        "mode": "off",
        "timeoutMs": 1500,
        "confidenceThreshold": 0.75,
        "maxRetries": 1
    }
}
