.pragma library

var data = {
    /** Enable OLED mode (true black background). @type {boolean} @default false */
    "oledMode": false,
    /** Enable light mode. @type {boolean} @default false */
    "lightMode": false,
    /** Base corner roundness in pixels. @type {number} @min 0 @max 100 @default 16 */
    "roundness": 16,
    /** Default font family. @type {string} @default "Roboto Condensed" */
    "font": "Roboto Condensed",
    /** Default font size in pixels. @type {number} @min 8 @max 72 @default 14 */
    "fontSize": 14,
    /** Monospace font family. @type {string} @default "Iosevka Nerd Font Mono" */
    "monoFont": "Iosevka Nerd Font Mono",
    /** Monospace font size in pixels. @type {number} @min 8 @max 72 @default 14 */
    "monoFontSize": 14,
    /** Tint icons with theme colors. @type {boolean} @default false */
    "tintIcons": false,
    /** Enable screen corners. @type {boolean} @default true */
    "enableCorners": true,
    /** Animation duration in milliseconds (legacy/global default). @type {number} @min 0 @max 2000 @default 300 */
    "animDuration": 300,
    /** Micro-interactions: hover tint, focus ring, press feedback. @type {number} @min 0 @max 500 @default 100 */
    "animInstant": 100,
    /** Quick transitions: toggles, checkboxes, small UI feedback. @type {number} @min 0 @max 500 @default 150 */
    "animQuick": 150,
    /** Standard transitions: popups, dropdowns, OSD, tooltips. @type {number} @min 0 @max 500 @default 300 */
    "animStandard": 300,
    /** Considered transitions: panels, sidebars, modals. @type {number} @min 0 @max 800 @default 400 */
    "animConsidered": 400,
    /** Cinematic transitions: shell startup, lockscreen, wallpaper crossfade. @type {number} @min 0 @max 1000 @default 600 */
    "animCinematic": 600,
    /** Easing for entrances (elements appearing). @type {string} @enum OutCubic,OutQuart,OutQuad @default "OutCubic" */
    "animEasingOut": "OutCubic",
    /** Easing for exits (elements disappearing). @type {string} @enum InCubic,InQuart,InQuad @default "InCubic" */
    "animEasingIn": "InCubic",
    /** Easing for state transitions (elements moving between states). @type {string} @enum InOutCubic,InOutQuart @default "InOutCubic" */
    "animEasingInOut": "InOutCubic",
    /** Shadow opacity. @type {number} @min 0 @max 1 @default 0.5 */
    "shadowOpacity": 0.5,
    /** Shadow color name. @type {string} @default "shadow" */
    "shadowColor": "shadow",
    /** Shadow X offset. @type {number} @min -100 @max 100 @default 0 */
    "shadowXOffset": 0,
    /** Shadow Y offset. @type {number} @min -100 @max 100 @default 0 */
    "shadowYOffset": 0,
    /** Shadow blur radius. @type {number} @min 0 @max 20 @default 1 */
    "shadowBlur": 1,
    /** Computer-use frame color 1 (empty = auto from theme, contrast-checked). @type {string} @default "" */
    "computerUseFrameColor1": "",
    /** Computer-use frame color 2 (empty = auto from theme, contrast-checked). @type {string} @default "" */
    "computerUseFrameColor2": "",
    /** Computer-use frame color 3 (empty = auto from theme, contrast-checked). @type {string} @default "" */
    "computerUseFrameColor3": "",
    /** Screen-recording start flash color. @type {string} @default "#FF2C2C" */
    "recordingFrameColor": "#FF2C2C",
    "srBg": {
        "label": "Background",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srPopup": {
        "label": "Popup",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 2],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srInternalBg": {
        "label": "Internal BG",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srBarBg": {
        "label": "Bar BG",
        "gradient": [["surfaceDim", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "surfaceDim",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 0.0
    },
    "srPane": {
        "label": "Pane",
        "gradient": [["surface", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surfaceBright",
        "halftoneBackgroundColor": "surface",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srCommon": {
        "label": "Common",
        "gradient": [["surface", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "background",
        "halftoneBackgroundColor": "surface",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srFocus": {
        "label": "Focus",
        "gradient": [["surfaceBright", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surfaceVariant",
        "halftoneBackgroundColor": "surfaceBright",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srPrimary": {
        "label": "Primary",
        "gradient": [["primary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overPrimaryContainer",
        "halftoneBackgroundColor": "primary",
        "border": ["primary", 0],
        "itemColor": "overPrimary",
        "opacity": 1.0
    },
    "srPrimaryFocus": {
        "label": "Primary Focus",
        "gradient": [["overPrimaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "primary",
        "halftoneBackgroundColor": "overPrimaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overPrimary",
        "opacity": 1.0
    },
    "srOverPrimary": {
        "label": "Over Primary",
        "gradient": [["overPrimary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "primaryContainer",
        "halftoneBackgroundColor": "overPrimary",
        "border": ["overPrimary", 0],
        "itemColor": "primary",
        "opacity": 1.0
    },
    "srSecondary": {
        "label": "Secondary",
        "gradient": [["secondary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overSecondaryContainer",
        "halftoneBackgroundColor": "secondary",
        "border": ["secondary", 0],
        "itemColor": "overSecondary",
        "opacity": 1.0
    },
    "srSecondaryFocus": {
        "label": "Secondary Focus",
        "gradient": [["overSecondaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "secondary",
        "halftoneBackgroundColor": "overSecondaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overSecondary",
        "opacity": 1.0
    },
    "srOverSecondary": {
        "label": "Over Secondary",
        "gradient": [["overSecondary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "secondaryContainer",
        "halftoneBackgroundColor": "overSecondary",
        "border": ["overSecondary", 0],
        "itemColor": "secondary",
        "opacity": 1.0
    },
    "srTertiary": {
        "label": "Tertiary",
        "gradient": [["tertiary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overTertiaryContainer",
        "halftoneBackgroundColor": "tertiary",
        "border": ["tertiary", 0],
        "itemColor": "overTertiary",
        "opacity": 1.0
    },
    "srTertiaryFocus": {
        "label": "Tertiary Focus",
        "gradient": [["overTertiaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "tertiary",
        "halftoneBackgroundColor": "overTertiaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overTertiary",
        "opacity": 1.0
    },
    "srOverTertiary": {
        "label": "Over Tertiary",
        "gradient": [["overTertiary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "tertiaryContainer",
        "halftoneBackgroundColor": "overTertiary",
        "border": ["overTertiary", 0],
        "itemColor": "tertiary",
        "opacity": 1.0
    },
    "srError": {
        "label": "Error",
        "gradient": [["error", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overErrorContainer",
        "halftoneBackgroundColor": "error",
        "border": ["error", 0],
        "itemColor": "overError",
        "opacity": 1.0
    },
    "srErrorFocus": {
        "label": "Error Focus",
        "gradient": [["overBackground", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "error",
        "halftoneBackgroundColor": "overErrorContainer",
        "border": ["overBackground", 0],
        "itemColor": "overError",
        "opacity": 1.0
    },
    "srOverError": {
        "label": "Over Error",
        "gradient": [["overError", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "errorContainer",
        "halftoneBackgroundColor": "overError",
        "border": ["overError", 0],
        "itemColor": "error",
        "opacity": 1.0
    }
}
